# Generated by Django 3.0.3 on 2020-03-12 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('Training', 'Training'), ('Workshop', 'Workshop')], max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.AttendeeType')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_end', models.DateField(default=django.utils.timezone.now)),
                ('time_start', models.TimeField(default=django.utils.timezone.now)),
                ('time_end', models.TimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default='The Ridge Wellness Center, 1 Ateljee Street, Randpark Ridge', max_length=255)),
                ('facilitator', models.CharField(default='Sonja Simak', max_length=50)),
                ('max_attendees', models.IntegerField(default=15)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventType')),
            ],
        ),
    ]
