# Generated by Django 3.0.3 on 2020-03-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('Training', 'Training'), ('Workshop', 'Workshop')], max_length=8)),
                ('description', models.CharField(max_length=150)),
                ('cost', models.CharField(blank=True, choices=[('Participant', 'Participant'), ('Non-Participant', 'Non-Participant'), ('Trainee', 'Trainee')], max_length=20)),
            ],
        ),
    ]
