# Generated by Django 3.0.3 on 2020-03-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtype',
            old_name='cost',
            new_name='cost_non_participant',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='attendee',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='cost_participant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='cost_trainee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='category',
            field=models.CharField(blank=True, choices=[('Training', 'Training'), ('Workshop', 'Workshop')], max_length=8),
        ),
    ]
