# Generated by Django 3.0.3 on 2020-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='cost',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='cost_non_participant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='cost_participant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='cost_trainee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
