# Generated by Django 3.0.3 on 2020-03-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200306_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('location', models.CharField(default='The Ridge Wellness Center, 1 Ateljee Street, Randpark Ridge', max_length=255)),
                ('facilitator', models.CharField(default='Sonja Simak', max_length=50)),
                ('max_attendees', models.IntegerField(default=15)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventType')),
            ],
        ),
    ]
