# Generated by Django 3.0.3 on 2020-03-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Testimonial',
            field=models.TextField(blank=True),
        ),
    ]
