# Generated by Django 3.0.3 on 2020-03-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200305_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Testimonial',
            new_name='testimonial',
        ),
    ]
