# Generated by Django 3.0.3 on 2020-03-14 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
