# Generated by Django 3.0.3 on 2020-03-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0002_mailinglist_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglist',
            old_name='Accept terms and conditions',
            new_name='accept_tc',
        ),
    ]
